MiNiFi Config Version: 3
Flow Controller:
  name: MiNiFi
  comment: ''
Core Properties:
  flow controller graceful shutdown period: 10 sec
  flow service write delay interval: 500 ms
  administrative yield duration: 30 sec
  bored yield duration: 10 millis
  max concurrent threads: 1
  variable registry properties: ''
FlowFile Repository:
  partitions: 256
  checkpoint interval: 2 mins
  always sync: false
  Swap:
    threshold: 20000
    in period: 5 sec
    in threads: 1
    out period: 5 sec
    out threads: 4
Content Repository:
  content claim max appendable size: 10 MB
  content claim max flow files: 100
  always sync: false
Provenance Repository:
  provenance rollover time: 1 min
  implementation: org.apache.nifi.provenance.MiNiFiPersistentProvenanceRepository
Component Status Repository:
  buffer size: 1440
  snapshot frequency: 1 min
Security Properties:
  keystore: ''
  keystore type: ''
  keystore password: ''
  key password: ''
  truststore: ''
  truststore type: ''
  truststore password: ''
  ssl protocol: ''
  Sensitive Props:
    key:
    algorithm: PBEWITHMD5AND256BITAES-CBC-OPENSSL
    provider: BC
Processors:
- id: a4b0e0c2-57fe-353d-0000-000000000000
  name: ConsumeMQTT
  class: org.apache.nifi.processors.mqtt.ConsumeMQTT
  max concurrent tasks: 1
  scheduling strategy: TIMER_DRIVEN
  scheduling period: 0 sec
  penalization period: 30 sec
  yield period: 1 sec
  run duration nanos: 0
  auto-terminated relationships list: []
  Properties:
    Broker URI: tcp://localhost:1883
    Client ID: nifid
    Connection Timeout (seconds): '60'
    Keep Alive Interval (seconds): '600'
    Last Will Message:
    Last Will QoS Level:
    Last Will Retain:
    Last Will Topic:
    MQTT Specification Version: '0'
    Max Queue Size: '200000'
    Password:
    Quality of Service(QoS): '1'
    SSL Context Service:
    Session state: 'true'
    Topic Filter: sensors
    Username:
Controller Services: []
Process Groups: []
Input Ports: []
Output Ports: []
Funnels: []
Connections:
- id: 04f4abb6-2c16-3bec-0000-000000000000
  name: ConsumeMQTT/Message/a12cc384-6778-3949-a6f9-e65b12832c14
  source id: a4b0e0c2-57fe-353d-0000-000000000000
  source relationship names:
  - Message
  destination id: a12cc384-6778-3949-a6f9-e65b12832c14
  max work queue size: 10000
  max work queue data size: 1 GB
  flowfile expiration: 0 sec
  queue prioritizer class: ''
Remote Process Groups:
- id: 190a3019-baa4-36f8-0000-000000000000
  name: ''
  url: http://demo.hortonworks.com:9090/nifi/
  comment: ''
  timeout: 30 sec
  yield period: 10 sec
  transport protocol: RAW
  proxy host: ''
  proxy port: ''
  proxy user: ''
  proxy password: ''
  local network interface: ''
  Input Ports:
  - id: a12cc384-6778-3949-a6f9-e65b12832c14
    name: From Hydraulic Rig
    comment: ''
    max concurrent tasks: 1
    use compression: false
  Output Ports: []
NiFi Properties Overrides: {}
